### ISSUE TITLE
localhost:9527无法打开

### ISSUE THREAD

**Issue by sunguangran** [zhoutaoo/SpringCloud-Admin#2]
npm run dev后浏览器一直加载，页面无法正常打开呢

**Comment by zhoutaoo** [comment]
请贴一下报错信息

**Comment by sunguangran** [comment]
![image](https://user-images.githubusercontent.com/2403503/64932126-86708000-d86f-11e9-9c08-4f9f7878eb5a.png)
没有报错，浏览器一直加载中

**Comment by zhoutaoo** [comment]
可以看浏览器console

**Comment by sunguangran** [comment]
![image](https://user-images.githubusercontent.com/2403503/64932484-f1bb5180-d871-11e9-913b-3992bdfecbfe.png)
貌似jwt token解析失败了

**Comment by zhoutaoo** [comment]
你登陆了吗？ localhost:9527/login一下

**Comment by sunguangran** [comment]
换了safari好了，chrome还是不行，不知道是不是和chrome版本有关系，chrome版本：77.0.3865.75
